# Ch `02`: Concept `02`

## Evaluating ops

Import TensorFlow:

In [1]:
import tensorflow as tf

Start with a 1x2 matrix:

In [5]:
x = tf.constant([[1, 2]])

print(-x,tf.negative(x))

tf.Tensor([[-1 -2]], shape=(1, 2), dtype=int32) tf.Tensor([[-1 -2]], shape=(1, 2), dtype=int32)


Let's negate it. Define the negation op to be run on the matrix:

In [6]:
neg_x = tf.negative(x)

It's nothing special if you print it out. In fact, it doesn't even perform the negation computation. Check out what happens when you simply print it:

In [7]:
print(neg_x)

tf.Tensor([[-1 -2]], shape=(1, 2), dtype=int32)


You need to summon a session so you can launch the negation op:

In [22]:
print(neg_x.numpy())
print(type(neg_x.numpy()))
print(type(neg_x))

print(neg_x.shape,neg_x.ndim)



[[-1 -2]]
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
(1, 2) 2
